<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_button_1</name>
   <tag></tag>
   <elementGuidId>ebaf880c-5155-402a-8415-46b48eb102a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[19]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(5) > div.course > div.add-section > button[type=&quot;button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>96285f49-c40f-43e0-8369-f9abd696ca89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7b1ec459-b95a-4b09-8074-f89c1f3fdb89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Añadir Seccion</value>
      <webElementGuid>61c71157-9214-4281-af03-2a410bc5224d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;main-container&quot;]/div[@class=&quot;course-box-container&quot;]/div[1]/div[5]/div[@class=&quot;course&quot;]/div[@class=&quot;add-section&quot;]/button[1]</value>
      <webElementGuid>f2352ee4-4497-42a0-9d1a-99a041680df4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[19]</value>
      <webElementGuid>e3efeae9-e0ba-4fe4-a773-5a1da6798c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div[5]/div/div[2]/button</value>
      <webElementGuid>7b28a33b-fab4-4d0a-93fd-c82533c03e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nuevo Curso 1'])[1]/following::button[1]</value>
      <webElementGuid>4d54cda7-7593-4b61-99b1-d674b45228e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Añadir Curso'])[1]/preceding::button[1]</value>
      <webElementGuid>f4644df9-4855-429b-b590-9435f32a43f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar Cursos'])[1]/preceding::button[2]</value>
      <webElementGuid>497f6d07-5ed5-4611-b0d1-ac7421e89765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/button</value>
      <webElementGuid>8fb88c67-6565-43b3-9411-c271fa9ff3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Añadir Seccion' or . = 'Añadir Seccion')]</value>
      <webElementGuid>d303902c-dbd9-4a6d-a11a-dce3cf1e701e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
