<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select</name>
   <tag></tag>
   <elementGuidId>7883ef2e-261a-4d4c-8fc2-cfb22896f9d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[3]/div/div[4]/div/div/li/div[2]/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fe51b5bb-de30-45f0-ae74-b33f8953ee4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>67891011121314151617181920</value>
      <webElementGuid>396876ac-407c-47be-a739-16bc5def26da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;main-container&quot;]/div[@class=&quot;section-edit-container&quot;]/div[@class=&quot;editable-section-container&quot;]/div[4]/div[@class=&quot;day-buttons&quot;]/div[@class=&quot;timeblock-container&quot;]/li[@class=&quot;timeblock-container-selector&quot;]/div[@class=&quot;hour-selection-container&quot;]/select[1]</value>
      <webElementGuid>512e6024-ea85-4249-9fe4-c8f6d34fa89b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div[4]/div/div/li/div[2]/select</value>
      <webElementGuid>f6543c9f-fb0e-4f9b-9fcd-1bf38d4dd061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Añadir'])[1]/following::select[4]</value>
      <webElementGuid>cb74c02a-76ff-4bf9-a073-37c63910f04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar'])[1]/preceding::select[2]</value>
      <webElementGuid>64eceb3c-7e82-4b0d-90a7-647089be25e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>9d84072c-38c4-415b-a5bd-3a745b0fde10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '67891011121314151617181920' or . = '67891011121314151617181920')]</value>
      <webElementGuid>583bedf0-fa89-4320-892c-21acaeee2c64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
