<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Filtrar por Das Libres_button</name>
   <tag></tag>
   <elementGuidId>df011eb0-46b0-4a10-a842-ae526c1f98e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a232c221-2018-4f0a-9cfd-849ff50e0e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ffe806a7-7e68-4b8c-af4b-1061a0ca680c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>277c35a0-7a4b-4017-819a-b2e5862c17b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Hora/Dia  6:00  7:00  8:00  9:00  10:00  11:00  12:00  13:00  14:00  15:00  16:00  17:00  18:00  19:00  20:00  Lunes  Martes Bases de Datos NRC: 2 07:00 - 10:15 Miercoles  Jueves Bases de Datos NRC: 2 12:00 - 14:15 Viernes  Sabado  Domingo  </value>
      <webElementGuid>c76f7aef-7338-4a15-9a07-4d815e5952ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;main-container&quot;]/div[@class=&quot;schedule-box&quot;]/div[@class=&quot;schedule-container&quot;]/div[@class=&quot;schedule-flex&quot;]/div[@class=&quot;two-schedules&quot;]/button[@class=&quot;button&quot;]</value>
      <webElementGuid>250c7eb1-c61e-4eca-bb23-5bea4fae8950</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>512b2fab-7b44-4c7b-8967-74d30512bba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div[2]/div/div/button</value>
      <webElementGuid>0335d1a5-db2d-4318-9a0a-526409c44301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtrar por Días Libres'])[1]/following::button[1]</value>
      <webElementGuid>900088c0-6e3d-4c4e-bab3-a4fe81e69af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GENERAR'])[1]/following::button[1]</value>
      <webElementGuid>0ba756fd-8ec9-4bbd-9274-0c40ce39b295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/button</value>
      <webElementGuid>b8573204-983b-4a85-bb21-f56ed94f108b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '  Hora/Dia  6:00  7:00  8:00  9:00  10:00  11:00  12:00  13:00  14:00  15:00  16:00  17:00  18:00  19:00  20:00  Lunes  Martes Bases de Datos NRC: 2 07:00 - 10:15 Miercoles  Jueves Bases de Datos NRC: 2 12:00 - 14:15 Viernes  Sabado  Domingo  ' or . = '  Hora/Dia  6:00  7:00  8:00  9:00  10:00  11:00  12:00  13:00  14:00  15:00  16:00  17:00  18:00  19:00  20:00  Lunes  Martes Bases de Datos NRC: 2 07:00 - 10:15 Miercoles  Jueves Bases de Datos NRC: 2 12:00 - 14:15 Viernes  Sabado  Domingo  ')]</value>
      <webElementGuid>ba6c9f91-ebec-4c05-a7c7-50baf6d4bd97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
