<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Filtrar por Das Libres_filter-button</name>
   <tag></tag>
   <elementGuidId>c3947ef3-5ff4-4041-b8ee-8ca6dd141bac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[2]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.filter-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0febcf91-8947-4b31-8797-4081792b5025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-button</value>
      <webElementGuid>8fb70a59-e03b-49de-b268-e7300be43d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NingunoLunesMartesMiercolesJuevesViernesSabadoDomingo</value>
      <webElementGuid>05f074d5-c1ee-4689-8d2b-88450e51953d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;main-container&quot;]/div[@class=&quot;schedule-box&quot;]/div[@class=&quot;action-buttons&quot;]/select[@class=&quot;filter-button&quot;]</value>
      <webElementGuid>a6c6c398-3888-4d90-898e-e88753e0c514</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div/select</value>
      <webElementGuid>457c930f-c471-4c5a-b4ff-ee36b1783c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtrar por Días Libres'])[1]/following::select[1]</value>
      <webElementGuid>9755ba54-714e-4537-a64a-667cdbb693ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GENERAR'])[1]/following::select[1]</value>
      <webElementGuid>23095fad-705f-494f-91e9-c7ff4f7d4226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>d72eae6b-c4f9-4fae-ad61-25848c3b4d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'NingunoLunesMartesMiercolesJuevesViernesSabadoDomingo' or . = 'NingunoLunesMartesMiercolesJuevesViernesSabadoDomingo')]</value>
      <webElementGuid>61e4865c-67ec-4f50-acb4-45521c355cf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
