<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Domingo_nav-buttons</name>
   <tag></tag>
   <elementGuidId>fea85fb1-27a2-4ff2-a3d1-ed77e0f7dec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[2]/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.nav-buttons</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1d7da997-6c6b-46e7-93b3-88423befedcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-buttons</value>
      <webElementGuid>22bbb93d-cba3-465b-ac7d-cb837597af6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;&lt;&lt;Guardar>>></value>
      <webElementGuid>884a274c-5f21-4d09-be32-5fb4d34bb5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;main-container&quot;]/div[@class=&quot;schedule-box&quot;]/div[@class=&quot;nav-buttons&quot;]</value>
      <webElementGuid>c11bf0d8-148e-43dc-8b47-93c615c1ac10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div[3]</value>
      <webElementGuid>54eb00c8-8f59-49c7-afd6-4306475f2c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]</value>
      <webElementGuid>6a7496d0-9b7b-4787-a537-70b54338e45f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '&lt;&lt;&lt;Guardar>>>' or . = '&lt;&lt;&lt;Guardar>>>')]</value>
      <webElementGuid>78bc1176-42ef-4241-b15f-e2367a4d2c02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
