<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Crear Cuenta_login-container</name>
   <tag></tag>
   <elementGuidId>1b7ed987-fe00-4fab-a3e5-41e2d8bdd553</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.login-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3523a9a7-f460-45bd-b517-ee6286f628a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-container</value>
      <webElementGuid>80810329-149a-49c4-a24d-97391d6aeb8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inicio de SesionIniciar SesionNo tienes cuenta? Crear Usuario</value>
      <webElementGuid>91569a3c-6bb6-4687-ab85-5f3ee82cf22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;main-container&quot;]/div[@class=&quot;login-container&quot;]</value>
      <webElementGuid>d30d4e66-aa93-4da0-9410-7ee93671705f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div</value>
      <webElementGuid>e8980eee-00db-4cf7-a868-72bd5b07806c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear Cuenta'])[1]/following::div[2]</value>
      <webElementGuid>5d139406-05a1-4078-a686-26f46dafab0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iniciar Sesion'])[1]/following::div[3]</value>
      <webElementGuid>6a788770-3220-4e11-9812-68097a4d4a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>dfa15926-78f6-4f34-a10e-0d148673b9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Inicio de SesionIniciar SesionNo tienes cuenta? Crear Usuario' or . = 'Inicio de SesionIniciar SesionNo tienes cuenta? Crear Usuario')]</value>
      <webElementGuid>a871a901-e604-424e-b0fb-f8ea5f666613</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
