<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ProfMaria_roles-usuario</name>
   <tag></tag>
   <elementGuidId>7deedc13-539a-45de-af7a-871c41f401c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='roles-usuario'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7b200924-25b3-4b76-a098-b4e87b8bddd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>formUsuarios</value>
      <webElementGuid>c812de55-fda9-42f2-9274-d9eb616d180e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>roles-usuario</value>
      <webElementGuid>3d395493-4cfb-41d3-ae77-65644be232e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>roles-usuario</value>
      <webElementGuid>63a92032-5ad5-4c31-9b80-98146003bd43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EstudianteProfesorAdmin</value>
      <webElementGuid>9f451475-1b06-4593-9106-1e53cc888dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formUsuarios&quot;)/div[@class=&quot;lista-usuarios&quot;]/div[@class=&quot;user&quot;]/select[@id=&quot;roles-usuario&quot;]</value>
      <webElementGuid>2e42a13c-52dd-47b3-b5c6-a4d6f69e70aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='roles-usuario'])[5]</value>
      <webElementGuid>e209d3f6-a7ba-4318-980e-eddfa623c4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formUsuarios']/div/div[5]/select</value>
      <webElementGuid>8dab108b-98ba-4776-b81c-e35c183a46db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ProfMaria'])[1]/following::select[1]</value>
      <webElementGuid>d6f2e902-851d-46a5-8223-4c97b16336df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar'])[4]/following::select[1]</value>
      <webElementGuid>d98c9d84-a86b-4d67-b8bc-ef3bcaaa324a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar'])[5]/preceding::select[2]</value>
      <webElementGuid>6f98bf02-5dba-444e-8607-9b2a55660a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar'])[1]/preceding::select[2]</value>
      <webElementGuid>0ce7a783-7572-4652-a70f-6ca3b8e93a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>90b1412f-acc1-4e46-a2e7-017127a0cce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@form = 'formUsuarios' and @name = 'roles-usuario' and @id = 'roles-usuario' and (text() = 'EstudianteProfesorAdmin' or . = 'EstudianteProfesorAdmin')]</value>
      <webElementGuid>2389e35c-9567-4539-ab4c-829a894f923d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
