<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Suite_CrearCuenta</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>981b9cbb-e1d8-47de-80e8-abdaf0d165c2</testSuiteGuid>
   <testCaseLink>
      <guid>7e2e7a6b-c6f7-4c16-a59d-23bbff91514f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CP-SYS-08</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>71ec07f7-ddfe-41af-b092-81fc0659b03a</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-7</value>
         </iterationEntity>
         <testDataId>Data Files/Data_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>71ec07f7-ddfe-41af-b092-81fc0659b03a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>f5427635-c7ad-4d3f-b7f0-4fa69c5cdbf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>71ec07f7-ddfe-41af-b092-81fc0659b03a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>0241ee2e-9e5e-48ea-b9b6-c2ae8d9401c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>71ec07f7-ddfe-41af-b092-81fc0659b03a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ResultadoEsperado</value>
         <variableId>a9af6d24-c03f-44b9-b4e0-04ebd075943c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
